using System.Collections.Generic;

namespace Idrissi.Blogging
{
  class Pages
  {
    public static Dictionary<string, bool> allowedPageIds = new Dictionary<string, bool>
    {
      ["post__a2b"] = true,
      ["post__abelian-bimodules"] = true,
      ["post__action-so-s-non-formal"] = true,
      ["post__acyclic-models"] = true,
      ["post__animation-braid"] = true,
      ["post__animation-peccot"] = true,
      ["post__bar-cobar-accepted"] = true,
      ["post__changes"] = true,
      ["post__codim-sc-accepted"] = true,
      ["post__conf-sp-woes"] = true,
      ["post__dark"] = true,
      ["post__digging"] = true,
      ["post__dns"] = true,
      ["post__ec-20-ans"] = true,
      ["post__eckmann-hilton"] = true,
      ["post__eventful-week"] = true,
      ["post__exam-template"] = true,
      ["post__facts"] = true,
      ["post__first-article"] = true,
      ["post__first-peccot"] = true,
      ["post__francais"] = true,
      ["post__gatsby"] = true,
      ["post__git-1-preliminaries"] = true,
      ["post__git-2-theory"] = true,
      ["post__git-3-practice"] = true,
      ["post__higher-structures"] = true,
      ["post__infinity-operads"] = true,
      ["post__inventiones"] = true,
      ["post__kafka-stars"] = true,
      ["post__lecture-notes"] = true,
      ["post__letter"] = true,
      ["post__mfo"] = true,
      ["post__milnor-moore"] = true,
      ["post__model-conf-spaces"] = true,
      ["post__model-conf-spaces-2"] = true,
      ["post__new-beginning"] = true,
      ["post__new-design"] = true,
      ["post__new-university-paris"] = true,
      ["post__next-stop-paris"] = true,
      ["post__peccot"] = true,
      ["post__peccot-covid"] = true,
      ["post__peccot-notes"] = true,
      ["post__peps"] = true,
      ["post__picture"] = true,
      ["post__select-exams"] = true,
      ["post__swiss-cheese-accepted"] = true,
      ["post__talk-paris"] = true,
      ["post__voronov-product"] = true,
      ["post__welcome"] = true,
      ["post__why-name-paris-7"] = true,
      ["post__ytm2016"] = true,
      ["post__zurich"] = true,
    };
  }
}
